### ISSUE TITLE
Drafts don't work

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-mailto#29]
#### Current behaviour

Currently if you're in the Mailto SPA, there's no way to save a draft:

- In the Inbox SPA, if you close the composer, the draft will automatically be saved.
- However, in the Mailto SPA, you can only close the window. But closing the window immediately won't allow saving the draft.

#### Proposed solution

Have a prompt to prevent the window from being closed immediately, asking the user if he/she wants to save the draft or not.

- If the user refuses to save the draft, just close the window.
- If the user chooses to save the draft, wait for the draft to be saved and then close the window.

**Comment by MichaelBailly** [comment]
I agree with this behaviour

**Comment by tuanlc** [comment]
I agree too as we discussed yesterday!

**Comment by chamerling** [comment]
@chamerling @MichaelBailly @tuanlc @huy-ta 

I looked on how to achieve this, here are the things/issues:

Using `window.onbeforeunload` can not work as easy as it seems. This will display a prompt if the user interacted with the page but this does not allows to customize the prompt message (this has been removed by all browsers to avoid 'spam'), nor does not allow to do any async operation as defined in the spec.

I tried several things, one is to do add some esn libs calls like:

-  Add `notificationFactory.weakSuccess('Success', 'Please save your message');` and try to have it displayed at the same time the prompt is displayed: This is not possible, it needs angularjs to digest and so the notification is not displayed. It is only displayed if the user clicks on `Cancel` on the prompt ie after the prompt is closed.

From the specs and from articles, there are some light solutions which may not fit our needs:

- Use `fetch` API with the `keep-alive` flag: limitation is about the size which must not exceed 64kb (sum of all the requests sent with this flag)
- Use `navigator.sendBeacon` which has also limitations as described https://dev.to/chromiumdev/sure-you-want-to-leavebrowser-beforeunload-event-4eg5 and https://stackoverflow.com/questions/40523469/navigator-sendbeacon-to-pass-header-information

The only solutions I see are:

- Having the automatic draft save feature enabled...
- Adding a save button in the composer which is displayed only in the mailto SPA and which the user can click to save

Also, there is no way to get the state of the message since it is scoped in the controller and see if it needs to be saved. We will need to change things at several places to get the status and being able to save the draft from the outside if we find a solution to do this from fetch, sendBeacon of whatever else...

**Comment by tuanlc** [comment]
> Having the automatic draft save feature enabled...

If I remember well, there is an issue with this feature, so it was disabled. @fabienmoyon may remember why?

**Comment by huy-ta** [comment]
> > Having the automatic draft save feature enabled...
> 
> If I remember well, there is an issue with this feature, so it was disabled. @fabienmoyon may remember why?

There was an issue from James. @RockyMeadow knows about this.

**Comment by huy-ta** [comment]
> Add notificationFactory.weakSuccess('Success', 'Please save your message'); and try to have it displayed at the same time the prompt is displayed: This is not possible, it needs angularjs to digest and so the notification is not displayed. It is only displayed if the user clicks on Cancel on the prompt ie after the prompt is closed.

I think we'll need to display the notification after the prompt has been closed. It will be awkward for the user at the first time because the prompt message is not clear due to modern browsers' restriction. But after the first time I think it'll be OK.

**Comment by chamerling** [comment]
> @chamerling I think we'll need to display the notification after the prompt has been closed. It will be awkward for the user at the first time because the prompt message is not clear due to modern browsers' restriction. But after the first time I think it'll be OK.

@huy-ta yes of course. A notification or a modal explaining things will be nice, with a button to save the email. I also think that in the current case we need a 'Save' button at the bottom near the 'Delete' one

**Comment by huy-ta** [comment]
@chamerling Yes I think that should work.

**Comment by chamerling** [comment]
I sent a couple of Draft PRs (no unit tests)

https://github.com/OpenPaaS-Suite/esn-frontend-mailto/pull/39
https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/102

**Comment by tlle14** [comment]
Hi @chamerling 

Retest failed!

![image](https://user-images.githubusercontent.com/69950655/92343230-645db680-f0ed-11ea-9df2-50f99cbae49e.png)

![draft](https://user-images.githubusercontent.com/69950655/92343189-485a1500-f0ed-11ea-946a-588dbeef8a29.gif)

**Comment by tlle14** [comment]
Hi @chamerling 

Retest pass with the expected! 

When a composer has content, close the tab or the windows, it displays a dialog with a notification to save a draft.
But when the composer doesn't have content, it displays a dialog without a notification. It seems right. 

![draft_dialog](https://user-images.githubusercontent.com/69950655/92346551-472de580-f0f7-11ea-93d9-d48f592c7486.gif)

But we should correct the notification content: `You should save email to not loose it` => Should be: `You should save the email to not lose it`

**Comment by tlle14** [comment]
Thank @huy-ta 

Retest pass

![image](https://user-images.githubusercontent.com/69950655/93059590-20ddec00-f69b-11ea-9f07-1085cb54f5a1.png)
