### ISSUE TITLE
Clicking on the email inside the email popup breaks the SPA

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-mailto#35]
#### Steps to reproduce

- Go to the Mailto SPA
- Enter a mail in the "To" field
- Hover over the email, then click on the email link in the popup

#### Current behaviour

The composer is no longer in fullscreen mode anymore, and a new composer tab is created.

![Mailto_Handler_Bug](https://user-images.githubusercontent.com/24670327/91542658-62a32e80-e948-11ea-9e00-b0936a104853.png)

#### Expected behaviour

The assignee of this issue should have some discussion about what the expected behaviour should be. The author suggest that a new browser tab that points to the Mailto SPA should be opened, just like in the other SPAs, and the current composer remains in fullscreen mode.

**Comment by billyfrost418** [comment]
Regarding the solution, my suggestion is to set the composer as a pop up initially instead of fullscreen mode. Since other message tabs might appear at the bottom of the page, this might collapse with the fullscreen composer. Besides, I think clicking on the email link should add a small tab at the bottom instead of new browser tab. It could be more convenient for users to navigate around different messages inside a page compare to multiple browser tabs. What is your opinion about this?

**Comment by huy-ta** [comment]
> Regarding the solution, my suggestion is to set the composer as a pop up initially instead of fullscreen mode. Since other message tabs might appear at the bottom of the page, this might collapse with the fullscreen composer. Besides, I think clicking on the email link should add a small tab at the bottom instead of new browser tab. It could be more convenient for users to navigate around different messages inside a page compare to multiple browser tabs. What is your opinion about this?

The current Mailto SPA is configured to deal with one instance of the composer only. You'll have to do _a lot_ of things if you want to have multiple composer instances in one single browser tab. Plus I'm not sure that's what we want.

**Comment by chamerling** [comment]
I am in favor of opening a new tab on email click since this is the way it is done in other SPAs.
