### ISSUE TITLE
Mailto app does not load correctly when the trailing slash is missing

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-mailto#49]
**Reproduction steps**
- receive an event confirmation
- click on the user's name
![image](https://user-images.githubusercontent.com/1465817/92491837-fd2a2a00-f1f2-11ea-8f2e-efa81cd48c74.png)

- the URL is https://server/mailto?uri=mailto:some@one.de (note: it's not mailto/ it's mailto)

**Current behaviour**
The application do not load. Error in console:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at fn (angular.js:10639)
    at xn.$get (angular.js:11466)
    at Object.s [as invoke] (angular.js:4220)
    at angular.js:4038
    at a (angular.js:4179)
    at Object.s [as invoke] (angular.js:4211)
    at Object.$get (angular.js:4073)
    at Object.s [as invoke] (angular.js:4220)
    at angular.js:4038
    at a (angular.js:4179)
```

**Expected behaviour**
The application loads.

**Comment by chamerling** [comment]
The error is on the inbox side: An old version of the mailto-handler is used which does not have the trailing slash

![Capture d’écran 2020-09-10 à 17 26 23](https://user-images.githubusercontent.com/264403/92754044-ca1a9e80-f38a-11ea-8e02-1dcd499d19c1.png)

Anyway, this is not the correct behavior in inbox which is due to https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/122. When https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/122 is merged, the inbox app will not open the mailto app anymore and will use the composer.

(The trailing slash is well defined as in https://github.com/OpenPaaS-Suite/esn-frontend-mailto-handler/blob/main/src/lib/directive.js#L71)

**Comment by chamerling** [comment]
The inbox application does not embed the mailto-handler directive and rely on the inbox composer only thanks to https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/122 (checked code from empty repository on inbox and calendar).

**Comment by chamerling** [comment]
Note to QA: Not deployed on production.

**Comment by tlle14** [comment]
Retest pass on Dev Environment

![retest_mailto](https://user-images.githubusercontent.com/69950655/93200580-24947000-f77a-11ea-9b31-36b65029c615.gif)
